#sfynx_auth:
#    theme: 
#        name: smoothness # {'flatlab','smoothness'} 
#        login: "SfynxSmoothnessBundle::Login\\"
#        layout: "SfynxSmoothnessBundle::Layout\\"
#        email:
#            registration:
#                from_email:
#                    address: contact@sfynx.fr
#                template: SfynxSmoothnessBundle:Login\\Registration:email.txt.twig
#            resetting:
#                from_email:
#                    address: contact@sfynx.fr
#                template: SfynxSmoothnessBundle:Login\\Resetting:email.txt.twig 
#        global:
#            layout: "SfynxSmoothnessBundle::Layout\\layout-global-cmf.html.twig"
#            css: "bundles/sfynxsmoothness/layout/screen-layout-global.css"
#        ajax:
#            layout: "SfynxSmoothnessBundle::Layout\\layout-ajax.html.twig"
#            css: "bundles/sfynxsmoothness/layout/screen-layout-ajax.css"
#        error:
#            route_name: ~ # error_404
#            html: "@SfynxSmoothnessBundle/Resources/views/Error/error.html.twig"
#        admin:
#            pc: "SfynxSmoothnessBundle::Layout\\Pc\\"
#            mobile: "SfynxSmoothnessBundle::Layout\\Mobile\\Admin\\"
#            css: "bundles/sfynxsmoothness/admin/screen.css"
#            home: "SfynxSmoothnessBundle:Home:admin.html.twig"  # SfynxAuthBundle:Frontend:index.html.twig
#            dashboard: "dashboard.default.html.twig"
#            grid:
#                img: "/bundles/sfynxsmoothness/admin/grid/img/"
#                css: ""   
#                type: simple
#                state_save: false
#                row_select: 'multi'  # multi, single
#                pagination: true 
#                pagination_type: "full_numbers"  # bootstrap, full_numbers, simple_numbers    
#                pagination_top: false
#                lengthmenu: 20
#                filters_tfoot_up: true
#                filters_active: false  
#            form:
#                builder: "SfynxSmoothnessBundle:Form"
#                template: "SfynxSmoothnessBundle:Form:fields.html.twig" 
#                css: ""  
#            flash: "SfynxSmoothnessBundle:Flash:flash.html.twig" 
#        front:
#            pc: "SfynxSmoothnessBundle::Layout\\Pc\\"
#            pc_path: "@SfynxSmoothnessBundle/Resources/views/Layout/Pc/"
#            mobile: "SfynxSmoothnessBundle::Layout\\Mobile\\"
#            mobile_path: "@SfynxSmoothnessBundle/Resources/views/Layout/Mobile/"
#            css: ""
#        connexion:
#            login: "SfynxSmoothnessBundle::Login\\Security\\login-layout.html.twig"
#            widget : "SfynxSmoothnessBundle::Login\\Security\\connexion-widget.html.twig" 